---
#  _     _           _  __          __     ___            _        
# | |__ (_)_ __   __| |/ /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# | '_ \| | '_ \ / _` | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | |_) | | | | | (_| | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |_.__/|_|_| |_|\__,_| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                      \_\          /_/                            
# get-archive
- name: get-archive | Download bind {{ bind.version }} at {{ bind.workingdir }}
  get_url:
    url:  "ftp://ftp.isc.org/isc/bind9/{{ bind.version }}/bind-{{ bind.version }}.tar.gz"
    dest: "{{ bind.workingdir }}/bind-{{ bind.version }}.tar.gz"

- name: get-archive | Extract {{ bind.bulidat }}/bind-{{ bind.version }}
  unarchive:
    src:     "{{ bind.workingdir }}/bind-{{ bind.version }}.tar.gz"
    dest:    "{{ bind.workingdir }}"
    creates: "{{ bind.workingdir }}/bind-{{ bind.version }}"
    copy:    "no"

