---
#  _     _           _  __          __     ___            _        
# | |__ (_)_ __   __| |/ /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# | '_ \| | '_ \ / _` | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | |_) | | | | | (_| | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |_.__/|_|_| |_|\__,_| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                      \_\          /_/                            
# tasks file for ar-bind-src
- { include: install-pkg.yml, when: bind.updateonly == false }
- { include: create-user.yml, when: bind.updateonly == false }
- { include: get-archive.yml }
- { include: compile-src.yml }
- { include: make-config.yml, when: bind.updateonly == false }
- { include: build-local.yml }
- { include: boot-script.yml }
- { include: port-config.yml }

- name: Start bind9
  when: bind.started == true
  service:
    name:  "{{ bind.initscript }}"
    state: "started"

- name: Stop bind9
  when: bind.started == false
  service:
    name:  "{{ bind.initscript }}"
    state: "stopped"

