---
#  _     _           _  __          __     ___                     _ _               
# | |__ (_)_ __   __| |/ /__ _ __ __\ \   / / |__   __ _ _ __   __| | | ___ _ __ ___ 
# | '_ \| | '_ \ / _` | / __| '__/ __| | / /| '_ \ / _` | '_ \ / _` | |/ _ \ '__/ __|
# | |_) | | | | | (_| | \__ \ | | (__| |/ / | | | | (_| | | | | (_| | |  __/ |  \__ \
# |_.__/|_|_| |_|\__,_| |___/_|  \___| /_/  |_| |_|\__,_|_| |_|\__,_|_|\___|_|  |___/
#                      \_\          /_/                                              
# handlers file for ar-bind-src
- name: Restart BIND
  when: bind.started == true
  service:
    name:   "{{ bind.initscript }}"
    state:   "restarted"

